import { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    id: "c001",
    name: "Zyla Health",
    domain: "zylahealth.com",
    industry: "HealthTech",
    stage: "Seed",
    location: "Bengaluru, India",
    foundedYear: 2022,
    employeeCount: 28,
    description:
      "AI-powered chronic disease management platform that delivers personalised care journeys for diabetes and hypertension patients via WhatsApp-native conversational UX.",
    founders: ["Priya Sharma", "Rohan Mehta"],
    lastFundingAmount: "$1.2M",
    traction: "12,000 MAU | 3× YoY growth",
    signalTags: ["AI-native", "WhatsApp-first", "India-focused", "B2C Health"],
    thesisScore: 88,
  },
  {
    id: "c002",
    name: "Axio Credit",
    domain: "axiocredit.in",
    industry: "Fintech",
    stage: "Seed",
    location: "Mumbai, India",
    foundedYear: 2021,
    employeeCount: 45,
    description:
      "Embedded BNPL and credit-line infrastructure for D2C brands, enabling instant checkout financing without redirects. Offers merchant SDK and real-time underwriting.",
    founders: ["Ankit Jain", "Shreya Kapoor"],
    lastFundingAmount: "$2.5M",
    traction: "85 merchant integrations | $4M GMV/month",
    signalTags: ["Embedded Finance", "BNPL", "D2C", "API-first"],
    thesisScore: 82,
  },
  {
    id: "c003",
    name: "LinguaFlow",
    domain: "linguaflow.io",
    industry: "EdTech",
    stage: "Pre-Seed",
    location: "Singapore",
    foundedYear: 2023,
    employeeCount: 11,
    description:
      "Adaptive language learning for Southeast Asian professionals using LLM-driven conversation simulations and spaced-repetition tailored to job-specific vocabulary.",
    founders: ["Min-jun Lee", "Anika Tan"],
    lastFundingAmount: "$400K",
    traction: "9,000 paying users | 78% D30 retention",
    signalTags: ["LLM-powered", "SEA Market", "EdTech", "B2C"],
    thesisScore: 74,
  },
  {
    id: "c004",
    name: "GridSense",
    domain: "gridsense.ai",
    industry: "CleanTech",
    stage: "Seed",
    location: "Chennai, India",
    foundedYear: 2022,
    employeeCount: 22,
    description:
      "IoT + ML platform for industrial energy optimisation. Provides real-time load forecasting and automated demand-response for factories and commercial buildings.",
    founders: ["Karthik Rajan", "Deepa Iyer"],
    lastFundingAmount: "$1.8M",
    traction: "18 enterprise pilots | 22% avg energy savings",
    signalTags: ["IoT", "Energy AI", "B2B", "Hardware-Software"],
    thesisScore: 79,
  },
  {
    id: "c005",
    name: "Stackwise",
    domain: "stackwise.dev",
    industry: "B2B SaaS",
    stage: "Seed",
    location: "Bengaluru, India",
    foundedYear: 2022,
    employeeCount: 19,
    description:
      "Developer-first internal tooling platform — think Retool but optimised for the Indian SMB market with native UPI integrations and vernacular language support.",
    founders: ["Vikram Nair", "Pooja Das"],
    lastFundingAmount: "$900K",
    traction: "230 active teams | $35K ARR",
    signalTags: ["No-code", "Developer Tools", "SMB-focused", "India-native"],
    thesisScore: 71,
  },
  {
    id: "c006",
    name: "OceanMind Analytics",
    domain: "oceanmind.sg",
    industry: "AI/ML",
    stage: "Pre-Seed",
    location: "Singapore",
    foundedYear: 2023,
    employeeCount: 8,
    description:
      "Foundation model for maritime logistics — predicts port congestion, vessel ETA deviations, and supply chain risk using AIS data and satellite imagery.",
    founders: ["Chen Wei", "Raj Kumar"],
    lastFundingAmount: "$350K",
    traction: "4 pilot contracts with tier-1 shipping lines",
    signalTags: ["Foundation Model", "Maritime", "Deep Tech", "B2B"],
    thesisScore: 85,
  },
  {
    id: "c007",
    name: "CureSight",
    domain: "curesight.health",
    industry: "HealthTech",
    stage: "Seed",
    location: "Hyderabad, India",
    foundedYear: 2021,
    employeeCount: 34,
    description:
      "AI ophthalmology platform that detects diabetic retinopathy and glaucoma from fundus images with 97% accuracy. Deployed in 120+ tier-2/3 clinics.",
    founders: ["Dr. Sunita Rao", "Kiran Patel"],
    lastFundingAmount: "$3.1M",
    traction: "120 clinics | 48,000 screens/month",
    signalTags: ["Medical AI", "Diagnostics", "Tier-2/3 India", "B2B Health"],
    thesisScore: 91,
  },
  {
    id: "c008",
    name: "BazaarPay",
    domain: "bazaarpay.co",
    industry: "Fintech",
    stage: "Series A",
    location: "Jakarta, Indonesia",
    foundedYear: 2020,
    employeeCount: 88,
    description:
      "Super-app payments layer for informal market vendors in Indonesia — digitises cash flows, offers micro-credit, and provides inventory financing for traditional warungs.",
    founders: ["Budi Santoso", "Maria Gunawan"],
    lastFundingAmount: "$8M",
    traction: "140,000 active merchants | $25M TPV/month",
    signalTags: ["Informal Economy", "SEA Fintech", "Micro-merchants", "MSME"],
    thesisScore: 78,
  },
  {
    id: "c009",
    name: "Helix Genomics",
    domain: "helixgenomics.in",
    industry: "DeepTech",
    stage: "Pre-Seed",
    location: "Pune, India",
    foundedYear: 2023,
    employeeCount: 14,
    description:
      "Low-cost CRISPR-based diagnostics startup making genomic testing accessible in resource-limited settings. First product targets tuberculosis drug-resistance profiling.",
    founders: ["Dr. Neha Chopra", "Arjun Bose"],
    lastFundingAmount: "$500K",
    traction: "2 government MoUs | ICMR validation underway",
    signalTags: ["CRISPR", "Diagnostics", "DeepTech", "Global Health"],
    thesisScore: 80,
  },
  {
    id: "c010",
    name: "ProcureAI",
    domain: "procureai.co",
    industry: "B2B SaaS",
    stage: "Seed",
    location: "Bengaluru, India",
    foundedYear: 2022,
    employeeCount: 31,
    description:
      "Autonomous procurement orchestration platform using AI agents to handle vendor discovery, RFQ management, and PO approvals — cutting procurement cycles by 60%.",
    founders: ["Siddharth Menon", "Tanya Gupta"],
    lastFundingAmount: "$2.0M",
    traction: "$1.2M ARR | 22 enterprise customers",
    signalTags: ["Agentic AI", "Procurement", "Enterprise SaaS", "Vertical AI"],
    thesisScore: 87,
  },
  {
    id: "c011",
    name: "NuFlux Energy",
    domain: "nuflux.energy",
    industry: "CleanTech",
    stage: "Seed",
    location: "Delhi, India",
    foundedYear: 2021,
    employeeCount: 40,
    description:
      "Second-life battery platform that repurposes used EV batteries into stationary energy storage systems for rural microgrids and telecom towers.",
    founders: ["Amit Khanna", "Richa Singh"],
    lastFundingAmount: "$3.5M",
    traction: "500 kWh deployed | 12 telecom tower contracts",
    signalTags: ["Battery Tech", "Circular Economy", "Energy Storage", "Impact"],
    thesisScore: 76,
  },
  {
    id: "c012",
    name: "HealthStack",
    domain: "healthstack.io",
    industry: "HealthTech",
    stage: "Seed",
    location: "Singapore",
    foundedYear: 2022,
    employeeCount: 26,
    description:
      "FHIR-native interoperability middleware for Southeast Asian hospital networks, enabling seamless EHR integration and cross-institutional patient data exchange.",
    founders: ["James Lim", "Preethi Nair"],
    lastFundingAmount: "$1.5M",
    traction: "6 hospital system integrations | Singapore MOH partner",
    signalTags: ["Interoperability", "FHIR", "B2B Health", "Infrastructure"],
    thesisScore: 83,
  },
  {
    id: "c013",
    name: "Kisan Saathi",
    domain: "kisansaathi.app",
    industry: "AI/ML",
    stage: "Pre-Seed",
    location: "Jaipur, India",
    foundedYear: 2023,
    employeeCount: 16,
    description:
      "Voice-first agri-advisory platform in 12 Indian languages, delivering personalised crop management advice, pest alerts, and mandi price data to smallholder farmers.",
    founders: ["Ramesh Yadav", "Kavya Mishra"],
    lastFundingAmount: "$300K",
    traction: "85,000 farmers onboarded | 4.2★ Play Store",
    signalTags: ["AgriTech", "Vernacular AI", "Voice-first", "Bharat-focused"],
    thesisScore: 72,
  },
  {
    id: "c014",
    name: "ZuriSpace",
    domain: "zurispace.co",
    industry: "DeepTech",
    stage: "Pre-Seed",
    location: "Bengaluru, India",
    foundedYear: 2023,
    employeeCount: 9,
    description:
      "Building low-cost earth observation microsatellites for precision agriculture and disaster response in South and Southeast Asia. Launch planned Q3 2025.",
    founders: ["Abhishek Patil", "Mehak Arora"],
    lastFundingAmount: "$600K",
    traction: "ISRO incubatee | 3 anchor LOIs",
    signalTags: ["Space Tech", "Earth Observation", "Deep Tech", "Hardware"],
    thesisScore: 68,
  },
  {
    id: "c015",
    name: "MindBridge Therapy",
    domain: "mindbridge.care",
    industry: "HealthTech",
    stage: "Pre-Seed",
    location: "Mumbai, India",
    foundedYear: 2023,
    employeeCount: 12,
    description:
      "AI-augmented mental health platform pairing users with licensed therapists and offering between-session CBT exercises via an empathic conversational AI.",
    founders: ["Dr. Ritu Arya", "Sameer Khan"],
    lastFundingAmount: "$250K",
    traction: "3,200 paying subscribers | NPS 71",
    signalTags: ["Mental Health", "AI + Human", "D2C HealthTech", "Subscription"],
    thesisScore: 77,
  },
  {
    id: "c016",
    name: "DataPilot",
    domain: "datapilot.ai",
    industry: "B2B SaaS",
    stage: "Seed",
    location: "Singapore",
    foundedYear: 2022,
    employeeCount: 23,
    description:
      "Natural language BI layer that sits on top of any data warehouse (Snowflake, BigQuery, Redshift) and lets non-technical teams query data in plain English or Mandarin.",
    founders: ["Kevin Yeo", "Nisha Pillai"],
    lastFundingAmount: "$1.8M",
    traction: "68 paying teams | $280K ARR",
    signalTags: ["NL2SQL", "BI Tools", "Multi-lingual AI", "Enterprise"],
    thesisScore: 81,
  },
  {
    id: "c017",
    name: "BuildFoundry",
    domain: "buildfoundry.in",
    industry: "Marketplace",
    stage: "Seed",
    location: "Bengaluru, India",
    foundedYear: 2021,
    employeeCount: 55,
    description:
      "B2B construction materials marketplace connecting SME contractors directly with factories, eliminating 3–4 distributor layers and delivering 18–25% cost savings.",
    founders: ["Varun Reddy", "Mohit Goel"],
    lastFundingAmount: "$4.2M",
    traction: "$6M GMV/month | 1,100 active contractors",
    signalTags: ["Construction Tech", "B2B Marketplace", "Supply Chain", "SME"],
    thesisScore: 75,
  },
  {
    id: "c018",
    name: "AeroMed Drones",
    domain: "aeromed.aero",
    industry: "DeepTech",
    stage: "Seed",
    location: "Hyderabad, India",
    foundedYear: 2021,
    employeeCount: 38,
    description:
      "Drone logistics network for last-mile medical supply delivery in hard-to-reach Indian geographies — blood, vaccines, and diagnostics in under 40 minutes.",
    founders: ["Capt. Suresh Kumar", "Dr. Leena Mathew"],
    lastFundingAmount: "$5M",
    traction: "3 state government contracts | 12,000 deliveries completed",
    signalTags: ["Drone Logistics", "MedTech", "Government", "Impact"],
    thesisScore: 82,
  },
  {
    id: "c019",
    name: "CarbonTrace",
    domain: "carbontrace.earth",
    industry: "CleanTech",
    stage: "Pre-Seed",
    location: "Singapore",
    foundedYear: 2023,
    employeeCount: 10,
    description:
      "Scope 3 carbon accounting SaaS for Asian manufacturing supply chains. Automates supplier data collection and produces audit-ready GHG reports aligned with GHG Protocol.",
    founders: ["Sophie Chen", "Arjun Nair"],
    lastFundingAmount: "$450K",
    traction: "14 enterprise beta customers | 2 Singapore brands pilot",
    signalTags: ["ESG", "Carbon Accounting", "Supply Chain", "B2B SaaS"],
    thesisScore: 79,
  },
  {
    id: "c020",
    name: "Revvio",
    domain: "revvio.io",
    industry: "B2B SaaS",
    stage: "Seed",
    location: "Bengaluru, India",
    foundedYear: 2022,
    employeeCount: 29,
    description:
      "Revenue intelligence platform for Indian SaaS companies — tracks pipeline health, forecast accuracy, and sales rep performance with CRM-native integrations.",
    founders: ["Manish Hegde", "Aditi Grover"],
    lastFundingAmount: "$1.1M",
    traction: "$420K ARR | 41 customers",
    signalTags: ["RevOps", "Sales AI", "CRM Integration", "SaaS for SaaS"],
    thesisScore: 78,
  },
];
